### ISSUE TITLE
Failed to find member with name 'ToDouble' in type 'Accord.Math.Matrix'

### ISSUE THREAD

**Issue by AndrewKaplanovsky** [cureos/accord#13]
Hi Anders, 

When trying to compile my UWP application in release mode I get the following error message:

error : Error: NUTC3059:Failed to find member with name 'ToDouble' and signature '0 1 1d d 1d 8' in type 'Accord.Math.Matrix' while resolving token 'a00004e' from module 'Accord.MachineLearning' while compiling method 'instance System.Double[] Accord.MachineLearning.BagOfWords.Accord.MachineLearning.IBagOfWords<System.String[]>.GetFeatureVector(System.String[])'.

When compiling the app in Debug mode everything is ok, no errors.

I'm using nugget libraries:
- shim 2.0.1
- shim.drawing 3.0.1
- portable accord.core 3.0.2.60302
- portable.accord.imaging 3.0.2.60302
- portable.accord.machinelearning 3.0.2.60302
- portable.accord.math 3.0.2.60302
- portable.accord.statistics 3.0.2.60302

Thank you,
Andrew

**Comment by anders9ustafsson** [comment]
@AndrewKaplanovsky What happens when you compile the code in Debug mode? Are you able to run the code sufficiently then?

Have you tested the 3.1.0-pre _Portable Accord_ packages to see if they build orrectly in Release mode?

**Comment by AndrewKaplanovsky** [comment]
Hi @anders9ustafsson, in my case when I compile in Debug mode (I mean 3.0.2.60302) everything works fine, no compilation errors and the app works perfectly. I'll try 3.1.0 and will let you know. Thank you.

**Comment by AndrewKaplanovsky** [comment]
Hi @anders9ustafsson, the same problem for _Portable Accord_ packages 3.1.0-pre, in release mode I get the following error: 

Error: NUTC302E:Internal Compiler Error: Token '2b000003' from module 'Accord.Statistics' could not be resolved while compiling method 'instance System.Double[][] Accord.Statistics.Analysis.CircularDescriptiveAnalysis.get_Array()'.

The debug version builds and works with no errors.
